name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Change to Heathcare directory
      run: cd Heathcare
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Install npm dependencies
      run: npm install

    - name: Run tests
      run: npm run test --if-present

    # Add your Azure deployment logic here
    - name: Deploy to Azure
      run: echo "Your Azure deploy command here"
